name: Release extension to marketplace

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs: {}

jobs:
  release:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Publish
        run: |
          npm install -g vsce
          vsce publish -p ${{ secrets.VSCE_PAT }}